apiVersion: apps/v1
kind: Deployment
metadata:
  name: adp-frontend
  labels:
    env: production
    version: v1
spec:
  selector:
    matchLabels:
      app: adp-frontend
  replicas: 3
  template:
    spec: 
      containers:
        - name: adp-frontend
          image: gcr.io/${PROD_PROJECT_ID}/adp-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
