apiVersion: v1
kind: Service
metadata:
  name: adp-frontend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: adp-frontend
  ports:
    - name:  http
      port:  4001
      targetPort:  4001
      protocol: TCP